name: check
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  check_make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cd src && make && ./db 100